### ISSUE TITLE
Use File_mdm exif

### ISSUE THREAD

**Issue by tonio48** [nbc-bravo/drupal-file_mdm#1]
Hello,
I don't understand how to use the module.
I want to display the exif informations and use them as filters in a view.
Thanks !!

**Comment by m4olivei** [comment]
Hi @tonio48 . This is a fork of https://www.drupal.org/project/file_mdm with a single [patch applied](https://www.drupal.org/node/3030820).

You probably don't want this fork, and instead should just use the [upstream Drupal module](https://www.drupal.org/project/file_mdm). All the usual module install instructions apply.
